FROM python:3.11

# Set the working directory
WORKDIR /app

COPY requirements.txt .

# Install dependencies
RUN apt-get update && apt-get install -y gcc libpq-dev netcat-openbsd \
    && pip install --no-cache-dir -r requirements.txt \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY . .

EXPOSE 8000

# running server
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
