version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: hello_db
      POSTGRES_USER: hello_user
      POSTGRES_PASSWORD: hello_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hello_net

  web:
    build: ./
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: hello_db
      POSTGRES_USER: hello_user
      POSTGRES_PASSWORD: hello_pass
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    networks:
      - hello_net
volumes:
  postgres_data:

networks:
  hello_net:
